### ISSUE TITLE
vm-youtube link is incorrect

### ISSUE THREAD

**Issue by hkumbum** [SoftwareEngineeringToolDemos/ICSE-2013-LAMBDAFICATOR#10]
vm-youtube link is incorrect.

**Comment by shashankgoudp** [comment]
You mean to say You tube link is not working or what exactly you mean when you say link is incorrect ?
I submitted the link which has the video created by me to show how the tool works..

**Comment by hkumbum** [comment]
Youtube link is written in text file rather than as a shortcut.

**Comment by shashankgoudp** [comment]
Corrected and submitted as a part of final project submission
