### ISSUE TITLE
Steps to install tool from scratch is not clear

### ISSUE THREAD

**Issue by hkumbum** [SoftwareEngineeringToolDemos/ICSE-2013-LAMBDAFICATOR#12]
Installation.txt on the desktop that says how to install the tool from scratch is not clear

**Comment by shashankgoudp** [comment]
As there is no binary for this tool, JDK 8 version has to be installed and Netbeans has to installed.
What else can we write in the installation steps ? please suggest

**Comment by shashankgoudp** [comment]
As there is no Binary for this tool, there cannot be any specific installation steps, other than installing Netbeans and JDK8.
