### ISSUE TITLE
History of project missing

### ISSUE THREAD

**Issue by hkumbum** [SoftwareEngineeringToolDemos/ICSE-2013-LAMBDAFICATOR#5]
Full history of project missing.

**Comment by shashankgoudp** [comment]
Can you elaborate on this ? What exactly do I have to put for history ?

**Comment by hkumbum** [comment]
If the project contains source code, does it contain the full history of the project (e.g., was the code properly forked or migrated from another repo)? [migration]. Hope you got it

**Comment by shashankgoudp** [comment]
When there is no source code, from where can we get history ?

**Comment by hkumbum** [comment]
If there is no source code, put wont-fix label, and provide explanation in the comments.
